examples/machine/README.md
examples/network_profile/README.md
examples/network_profile/simple/README.md
examples/network_profile/simple/main.tf
examples/network_profile/simple/terraform.tfvars.sample
examples/network_profile/simple/variables.tf
examples/network_profile/simple/versions.tf
examples/project/README.md
examples/zone/README.md

Add example for simple network_profile

---

examples/machine/README.md
examples/network_profile/README.md
examples/network_profile/simple/README.md
examples/project/README.md
examples/zone/README.md

Fix relative links in example README.md files

---

examples/cloud_account_aws/main.tf
examples/cloud_account_gcp/main.tf
examples/cloud_account_vsphere/main.tf
examples/machine-network/main.tf
examples/machine/main.tf
examples/network_profile/isolation_with_external_subnet/main.tf
examples/network_profile/isolation_with_security_group/main.tf
examples/network_profile/isolation_with_subnet/main.tf
examples/network_profile/security_groups/main.tf
examples/network_profile/simple/main.tf
examples/project/main.tf
examples/wordpress/main.tf
examples/zone/main.tf

Fix formatting and names in examples

---

vra/data_source_cloud_account_gcp.go
vra/data_source_cloud_account_gcp_test.go
vra/provider.go
vra/resource_cloud_account_gcp.go

Add data source for GCP cloud account

---

.golangci.yml
vra/client.go
vra/constraints.go
vra/data_source_cloud_account_aws.go
vra/data_source_cloud_account_azure.go
vra/data_source_cloud_account_gcp.go
vra/data_source_fabric_network_test.go
vra/data_source_image_test.go
vra/data_source_network.go
vra/data_source_network_domain_test.go
vra/data_source_project.go
vra/data_source_zone.go
vra/links.go
vra/rules.go
vra/structure.go

Note: some of the dead code was commented out and will be
addressed in a subsequent change.

Fix lint errors

---

docker/Dockerfile

Remove legacy Dockerfile

---

vra/provider_test.go
vra/resource_image_profile_test.go
vra/resource_machine_test.go
vra/resource_project_test.go

Signed-off-by: Prativa Bawri <bawrip@bawrip-a02.vmware.com>

Resource image profile acc test

---

vra/provider_test.go
vra/resource_storage_profile_azure_test.go

Signed-off-by: Prativa Bawri <bawrip@bawrip-a02.vmware.com>

Fix storage profile azure acc test

---

vra/provider_test.go
vra/resource_machine.go
vra/resource_machine_test.go

Adding machine day 2 resize operation as part of update machine

---

examples/machine/README.md
examples/machine/main.tf
examples/machine/terraform.tfvars.sample
examples/machine/variables.tf
go.mod
go.sum
vra/nics.go
vra/resource_machine.go
vra/resource_machine_test.go
website/docs/r/machine.html.markdown

Update sdk to 0.2.0 and fix resource_machine test

---

.gitignore
main.go
scripts/release.sh

Add script to release binaries to github

---

go.mod
go.sum
vra/resource_block_device.go

Fixes #87 with https://github.com/vmware/vra-sdk-go/pull/6

Handle 204 response for delete block device

---

examples/deployment/README.md
examples/deployment/blueprint/README.md
examples/deployment/blueprint/main.tf
examples/deployment/blueprint/terraform.tfvars.sample
examples/deployment/blueprint/variables.tf
examples/deployment/blueprint/versions.tf
examples/deployment/catalog_item/README.md
examples/deployment/catalog_item/main.tf
examples/deployment/catalog_item/terraform.tfvars.sample
examples/deployment/catalog_item/variables.tf
examples/deployment/catalog_item/versions.tf
examples/deployment/no_resources/README.md
examples/deployment/no_resources/main.tf
examples/deployment/no_resources/terraform.tfvars.sample
examples/deployment/no_resources/variables.tf
examples/deployment/no_resources/versions.tf
vra/catalog_item_version.go
vra/data_source_catalog_item.go
vra/data_source_catalog_item_test.go
vra/data_source_deployment.go
vra/data_source_deployment_test.go
vra/expense.go
vra/provider.go
vra/provider_test.go
vra/resource.go
vra/resource_deployment.go
vra/resource_deployment_test.go
vra/resource_reference.go
vra/structure.go

Add deployment resource and data sources for catalog_item and deployment

---

examples/network_profile/isolation_with_external_subnet/main.tf
examples/network_profile/isolation_with_subnet/main.tf
vra/data_source_network_profile.go
vra/data_source_network_profile_test.go
vra/provider.go
vra/resource_network_profile.go
vra/resource_network_profile_test.go

Rename network_profile arguments related to isolation to match with the IaaS api arguments
Fixes #83 

Add network_profile data source

---

vra/load_balancer_targets.go
vra/provider_test.go
vra/resource_load_balancer.go
vra/resource_load_balancer_test.go

Fix target links in load balancer

---

examples/deployment/blueprint/README.md
examples/deployment/blueprint/main.tf
vra/structure.go
vra/structure_test.go

Fix crash issue during deployment requests with non-string inputs

---

vra/data_source_region_enumeration.go

Fix nil reference access

---

README.md

Also added a link to point to vRA 7 provider.
Signed-off-by: Carlos Tronco <cars@lostroncos.org>

updated Readme.md to specify version supported

---

vra/resource_block_device.go
vra/resource_cloud_account_aws.go
vra/resource_cloud_account_azure.go
vra/resource_cloud_account_gcp.go
vra/resource_cloud_account_nsxt.go
vra/resource_cloud_account_nsxv.go
vra/resource_cloud_account_vmc.go
vra/resource_cloud_account_vsphere.go
vra/resource_deployment.go
vra/resource_flavor_profile.go
vra/resource_image_profile.go
vra/resource_load_balancer.go
vra/resource_machine.go
vra/resource_network.go
vra/resource_network_profile.go
vra/resource_project.go
vra/resource_storage_profile.go
vra/resource_storage_profile_aws.go
vra/resource_storage_profile_azure.go
vra/resource_zone.go

Add import feature to all vra resources

---

examples/multiple_resources_deployment/README.md
examples/multiple_resources_deployment/main.tf
examples/multiple_resources_deployment/terraform.tfvars.sample
examples/multiple_resources_deployment/variables.tf
go.mod
go.sum
vra/data_source_network.go
vra/resource_block_device.go
vra/resource_load_balancer.go
vra/resource_machine.go
vra/resource_network.go

Adding deployment id to machine, network, load balancer and block device
resources to enable creating deployments with multiple resources

Fix for https://github.com/vmware/terraform-provider-vra/issues/113

---

examples/multiple_resources_deployment/README.md
website/docs/r/machine.html.markdown

Update machine doc and multiple resources deployment example doc

---

examples/machine/main.tf
vra/provider_test.go
vra/resource_machine.go
vra/resource_machine_test.go

Recreate machine resource when image is updated

---

vra/data_source_project.go
vra/data_source_project_test.go

Fix project data source (#110)

---

examples/blueprint/README.md
examples/blueprint/main.tf
examples/blueprint/terraform.tfvars.sample
examples/blueprint/variables.tf
examples/blueprint/versions.tf
vra/data_source_blueprint.go
vra/data_source_blueprint_test.go
vra/provider.go
vra/provider_test.go
vra/resource_blueprint.go
vra/resource_blueprint_test.go

Add blueprint resource and data source (#99) (#104)

---

examples/block-device/README.md
examples/block-device/variables.tf
go.mod
go.sum
vra/data_source_block_device.go
vra/data_source_block_device_test.go
vra/provider.go
vra/resource_block_device.go
website/docs/d/block_device.html.markdown
website/docs/r/block_device.html.markdown

Data source block device

---

vra/resource_block_device.go

adding error check for deployment id in block-device in vra on-prem

---

examples/deployment/blueprint/main.tf
examples/deployment/blueprint/terraform.tfvars.sample
examples/deployment/blueprint/variables.tf
examples/deployment/catalog_item/main.tf
vra/resource_blueprint.go
vra/resource_deployment.go

Changes to inputs in deployment resource are now applied on the existing deployment
using update action.

Add support for update action on deployment (#100)

---

go.mod
go.sum
vra/data_source_vra_machine.go
vra/data_source_vra_machine_test.go
vra/provider.go

Adding machine data source

---

examples/block-device/main.tf
go.mod
go.sum
vra/data_source_block_device.go
vra/data_source_region_enumeration.go
vra/resource_block_device.go
website/docs/d/block_device.html.markdown
website/docs/r/block_device.html.markdown

Support for resize block device vra on prem and cloud

https://github.com/vmware/terraform-provider-vra/issues/132

---

docs/get_token.sh
docs/install_provider.md

- Adding correct plugins path under Linux install instructions
- Changing password prompt to silent. Reformatting newlines to Linux more like structure
- removing echoes that were added for debugging

Multiple minor changes

---

examples/deployment/blueprint/main.tf
examples/deployment/catalog_item/main.tf

Add output samples in deployment resource examples

---

scripts/release.sh

Add check for GITHUB_TOKEN environment variable in release script

---

vra/resource_deployment.go

Currently, if a deployment fails during create, provider reports that
deployment resource is added, however the state file has the correct
status i.e. CREATE_FAILED.
With this change, if a deployment is failed during create, the apply
command shows the failure message and also the state file is updated
with current state of deployment.

Show failure message if deployment creation fails

---

vra/structure.go

Check deployment last_request for empty inputs

---

.github/workflows/golangci-lint.yml
.github/workflows/release.yml
.gitignore
.goreleaser.tmpl
.goreleaser.yml

Add new release mechanism via goreleaser and github actions

---

vra/resource_machine.go

All the disks attached to machine resource are not saved to
'disks_list' attribute which includes those block devices attached
using the 'disks' attribute as well as the boot-disk, CD and Floppy
disks that are auto created with the machine resource.

Fix #146 by saving machine disks in state file

---

vra/resource_project.go

Fix Project read issue when there are no constraints

---

examples/project/main.tf
vra/constraints.go
vra/constraints_test.go
vra/data_source_project_test.go
vra/resource_project.go
vra/resource_project_test.go

This commit fixes the issue seen on vRA 8.1, when there are no
constraints in the project.
Issues fixed: #235

Fix Project read issue when the constraints size is 0

---

go.mod
go.sum
vra/data_source_fabric_storage_account_azure.go
vra/data_source_fabric_storage_account_azure_test.go
vra/provider.go
vra/provider_test.go

Add data source for fabric Azure storage account

---

go.mod
go.sum
vra/resource_cloud_account_nsxt.go
vra/resource_cloud_account_nsxv.go

Update vRA SDK to v0.2.15

---

vra/resource_zone.go

Add folder support to vra_zone resource for vSphere cloud accounts

---

vra/resource_cloud_account_nsxt.go
vra/resource_cloud_account_nsxv.go
vra/resource_cloud_account_vmc.go
vra/resource_cloud_account_vsphere.go

Increase timeout to create vSphere, VMC, and NSX-T/V cloud accounts

---

vra/data_source_cloud_account_aws.go
vra/data_source_cloud_account_azure.go

Add additional attributes to cloud account AWS and Azure data sources

---

vra/data_source_cloud_account_aws.go
vra/data_source_cloud_account_azure.go
vra/data_source_cloud_account_gcp.go
vra/data_source_cloud_account_nsxt.go
vra/data_source_cloud_account_nsxv.go
vra/data_source_cloud_account_vmc.go
vra/resource_cloud_account_aws.go
vra/resource_cloud_account_azure.go
vra/resource_cloud_account_gcp.go
vra/resource_cloud_account_nsxt.go
vra/resource_cloud_account_nsxv.go
vra/resource_cloud_account_vmc.go
vra/resource_cloud_account_vsphere.go

Add metadata attributes to cloud account resources

---

examples/storage_profile/aws_with_ebs/main.tf
examples/storage_profile/aws_with_instance_store/main.tf
examples/storage_profile/azure_with_managed_disks/main.tf
examples/storage_profile/azure_with_unmanaged_disks/main.tf
vra/data_source_storage_profile_aws.go
vra/data_source_storage_profile_aws_test.go
vra/data_source_storage_profile_azure.go
vra/data_source_storage_profile_azure_test.go
vra/provider.go
vra/provider_test.go
vra/resource_storage_profile_test.go

Signed-off-by: Sagar <bhadgaonkars@vmware.com>

Add data sources for AWS and Azure Storage Profiles

---

examples/cloud_account_vmc/main.tf
examples/cloud_account_vsphere/main.tf
vra/data_source_cloud_account_aws.go
vra/data_source_cloud_account_azure.go
vra/data_source_cloud_account_nsxt.go
vra/data_source_cloud_account_vsphere.go
website/docs/d/cloud_account_aws.html.markdown
website/docs/d/cloud_account_azure.html.markdown
website/docs/d/cloud_account_gcp.html.markdown
website/docs/d/cloud_account_nsxt.html.markdown
website/docs/d/cloud_account_nsxv.html.markdown
website/docs/d/cloud_account_vmc.html.markdown
website/docs/d/cloud_account_vsphere.html.markdown
website/docs/r/cloud_account_aws.html.markdown
website/docs/r/cloud_account_azure.html.markdown
website/docs/r/cloud_account_gcp.html.markdown
website/docs/r/cloud_account_nsxt.html.markdown
website/docs/r/cloud_account_nsxv.html.markdown
website/docs/r/cloud_account_vmc.html.markdown
website/docs/r/cloud_account_vsphere.html.markdown

Added docs for data source and resources of cloud accounts
Signed-off-by: Zhi Zhu <zzhi@vmware.com>

Add docs for cloud accounts

---

.github/workflows/golangci-lint.yml
.github/workflows/release.yml

Bump up golangci-lint-action version to v2

---

website/docs/d/vra_block_device.html.markdown

Reformatted some lines.
Signed-off-by: ClaraChang <clarac@ABCandM.com>

Reformatted some lines.

---

vra/resource_flavor_profile.go

Fix import functionality of vra_flavor_profile resource by populating
flavor_mapping and region_id correctly.
Fixes #287.

Fix vra_flavor_profile resource import/read functionality

---

vra/resource_deployment.go

Fix #317 by making deployment owner as computed

---

vra/data_source_project.go
vra/resource_project.go
website/docs/d/vra_project.html.markdown
website/docs/r/vra_project.html.markdown

Added custom properties in project resource and datasource
Updated the examples and README
Signed-off-by: Xiaosheng Wu <wxiaosheng@vmware.com>

[issue-291] Add Custom properties in resourceProject

---

.github/workflows/stale.yml

Add stale github action for Issues and PRs

---

website/docs/d/region.html.markdown

[339] vra_region documentation under Data Source is blank

---

website/docs/r/vra_project.html.markdown

Due to the limitation of IAAS API to update project and provide workaround.
Signed-off-by: Daniel Chuang <tchuang@vmware.com>

Update the Project Resource page

---

vra/data_source_region.go
website/docs/d/vra_region.html.markdown

* Add descriptions to schema
* Return proper errors when region and/or cloud accounts are not found
* Fix retrieving a region using cloud account id and region name

Several fixes for the data source region

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/stale.yml
NOTICE

* Adds a NOTICE file
* Update issue's templates
* Tunes stale github action properties

Add NOTICE file

---

CONTRIBUTING.md

Update CONTRIBUTING.md to reflect main branch

---

vra/data_source_zone.go
vra/data_source_zone_test.go
vra/resource_zone.go
website/docs/d/vra_zone.html.markdown
website/docs/r/vra_zone.html.markdown

* Updates `vra_zone` datasource and resource attributes
* Adds the ability to manage the `compute resources` associated with the `vra_zone` (Fixes https://github.com/vmware/terraform-provider-vra/issues/278)

Update `zone` datasource and resource

---

vra/data_source_fabric_datastore_vsphere.go
vra/data_source_fabric_datastore_vsphere_test.go
website/docs/d/fabric_datastore_vsphere.html.markdown

Update `fabric_datastore_vsphere` data source attributes

---

examples/project/main.tf
vra/data_source_project.go
vra/resource_project.go
website/docs/d/vra_project.html.markdown
website/docs/r/vra_project.html.markdown

In order to have a good experience with our community, we recommend that you read the [contributing guidelines](https://github.com/vmware/terraform-provider-vra/blob/main/CONTRIBUTING.md) for making a pull request.
Adds `projectPlacementPolicy` to `vra_project` resource as `placement_policy`.
**Context of the Pull Request***
- Add optional `placement_policy` to `vra_project` resource / datasource.
- Updates example for `vra_project` resource
- Updates documentation for `vra_project` resource / datasource
Issue Number: #414 

Add `placement_policy` to `vra_project`

---

vra/regions.go

Add region name

---

examples/fabric_datastore_vsphere/README.md
examples/fabric_datastore_vsphere/main.tf
examples/fabric_datastore_vsphere/terraform.tfvars.sample
examples/fabric_datastore_vsphere/variables.tf
vra/provider.go
vra/provider_test.go
vra/resource_fabric_datastore_vsphere.go
vra/resource_fabric_datastore_vsphere_test.go
website/docs/r/vra_fabric_datastore_vsphere.html.markdown

Add a new `vra_fabric_datastore_vsphere` resource. Fixes #353.

Add `fabric_datastore_vsphere` resource

---

.goreleaser.yml
terraform-registry-manifest.json

Add Terraform Registry manifest file template and include it at the goreleaser configuration.

Add Terraform Registry manifest file

---

examples/cloud_account_vmc/main.tf

Fix vmc region enumeration example

---

.github/workflows/golangci-lint.yml
.github/workflows/release.yml
.golangci.yml

Remove deprecated linters and upgrade to golangci-lint to v1.50.0

---

vra/data_source_image.go
website/docs/d/vra_image.html.markdown

* Update vra_image data source attributes
* Allow searching an image by id
Fixes #444

Update vra_image data source

---

vra/data_source_blueprint.go

* Update  attributes
* Fix lookup logic by id
Fixes #434 

Fix vra_blueprint datasource lookup by id

---

examples/flavor_profile/main.tf
examples/flavor_profile/variables.tf
vra/resource_flavor_profile.go
website/docs/r/vra_flavor_profile.html.markdown

Update vra_profile resource attribute descriptions, examples, and documentation.
Fixes #445 

Update vra_flavor_profile attributes

---

vra/catalog_item_version.go
vra/data_source_catalog_item.go
website/docs/d/vra_catalog_item.html.markdown

* Update vra_catalog_item data source attributes
* Allow specifying the project_id when searching a catalog item by id
Fixes #310 #430 

Add project_id to vra_catalog_item datasource lookup

---

examples/network_ip_range/main.tf
vra/resource_network_ip_range.go
vra/resource_network_ip_range_test.go
website/docs/r/vra_network_ip_range.html.markdown

[vra_network_ip_range] Allow list of fabric network ids

---

examples/cloud_account_vsphere/main.tf
vra/data_source_cloud_account_vmc_test.go
vra/data_source_cloud_account_vsphere.go
vra/data_source_cloud_account_vsphere_test.go
vra/data_source_region_enumeration.go
vra/data_source_region_enumeration_test.go
vra/data_source_region_enumeration_vsphere.go
vra/data_source_region_enumeration_vsphere_test.go
vra/resource_cloud_account_vmc_test.go
vra/resource_cloud_account_vsphere.go
vra/resource_cloud_account_vsphere_test.go
website/docs/d/vra_region_enumeration.html.markdown
website/docs/d/vra_region_enumeration_vsphere.html.markdown
website/docs/r/vra_cloud_account_vsphere.html.markdown

Rename attribute dcid to dc_id

---

examples/integration/README.md
examples/integration/main.tf
examples/integration/terraform.tfvars.sample
examples/integration/variables.tf
examples/integration/versions.tf
vra/provider.go
vra/provider_test.go
vra/resource_integration.go
vra/resource_integration_test.go
website/docs/r/vra_integration.html.markdown

Add vra_integration resource

---

SECURITY.md

Add Security Release Process document

---

SECURITY.md

Fix security email

---

vra/data_source_catalog_item.go

Fix vra_catalog_item datasource lookup bug

---

go.mod
go.sum
vra/data_source_region_enumeration.go
vra/data_source_region_enumeration_aws.go
vra/data_source_region_enumeration_azure.go
vra/data_source_region_enumeration_gcp.go
vra/data_source_region_enumeration_vmc.go
vra/data_source_region_enumeration_vsphere.go
vra/resource_cloud_account_aws.go
vra/resource_cloud_account_azure.go
vra/resource_cloud_account_gcp.go
vra/resource_cloud_account_nsxt.go
vra/resource_cloud_account_nsxv.go
vra/resource_cloud_account_vmc.go
vra/resource_cloud_account_vsphere.go
vra/resource_integration.go

Upgrade vra-sdk-go to v0.6.0

---

examples/project/main.tf
vra/data_source_project.go
vra/resource_project.go
website/docs/d/vra_project.html.markdown
website/docs/r/vra_project.html.markdown

Add supervisor roles to project datasource and resource

---

vra/data_source_cloud_account_vsphere.go
vra/data_source_region_enumeration.go
vra/data_source_region_enumeration_vsphere.go
vra/resource_cloud_account_vsphere.go

Remove deprecated dcid attribute

---

vra/resource_cloud_account_vsphere.go

Fix #481 for vSphere only.
Other cloud_account_* resources have similar issues, but I do not have the setup to test them.

Add missing fields

---

vra/resource_cloud_account_nsxt.go
vra/resource_cloud_account_nsxv.go
vra/resource_cloud_account_vmc.go
vra/resource_cloud_account_vsphere.go

Fix update for vSphere/VMC/NSX-T/NSX-V cloud accounts

---

go.mod

Switch to go 1.N.P version syntax.

Upgrade to go 1.23.2

---

.github/workflows/stale.yml

- Correct formatting.
- [Pin GitHub Actions to release commit SHA](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).

chore(gh): update stale workflow

---

.github/workflows/lock.yml

Adds workflow to lock issues and pull requests closed after x days.

chore(gh): add lock workflow

---

CODE-OF-CONDUCT.md

chore: update code of conduct

---

.github/labeler-issues.yml
.github/workflows/issues.yml

Add issue labels.
Issue Number: N/A

chore(gh): add issue labels

---

.github/labeler-pull-requests.yml
.github/workflows/pull-requests.yml

Add pull request labels.
Issue Number: N/A

chore(gh): add pull request labels

---

.github/workflows/release.yml

- Update `actions/setup-go` from v4.x to v5.1.0
- Update `golangci/golangci-lint-actiono` from v3 to v6.1.1.
- [Pin GitHub Actions to release commit SHA](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).

chore(gh): update release workflow

---

vra/resource_machine.go
website/docs/r/vra_machine.html.markdown

Some commits from PR #542 were not compliant with our [Developer Certificate of Origin](https://cla.vmware.com/dco). This PR reverts those commits.

Recreate commits from PR #542

---

GNUmakefile

Remove `website` and `website-test` targets from Makefile

Remove website and website-test targets

---

docs/data-sources/vra_catalog_item.md
docs/resources/vra_catalog_item_vm_image.md
docs/resources/vra_catalog_item_vro_workflow.md
go.mod
go.sum
vra/catalog_item_helper.go
vra/data_source_catalog_item.go
vra/provider.go
vra/resource_catalog_item_vm_image.go
vra/resource_catalog_item_vro_workflow.go

* Add vra_catalog_item_vm_image resource and datasource
* Add vra_catalog_item_vro_workflow resource and datasource

Add a few new catalog item resources and datasources
