vra/resource_block_device.go
vra/resource_load_balancer.go
vra/resource_machine.go
vra/resource_network.go

Resources that take longer to create and destroy can now use the timeouts block
with custom timeouts for create, delete and update where applicable.
Supported resources are: vra_machine, vra_network, vra_block_device, vra_load_balancer.

Add support for customizable timeouts for long running operations

---

examples/cloud_account_vmc/main.tf
examples/cloud_account_vmc/terraform.tfvars.sample
examples/cloud_account_vmc/variables.tf
examples/cloud_account_vsphere/main.tf
examples/cloud_account_vsphere/terraform.tfvars.sample
examples/cloud_account_vsphere/variables.tf
vra/data_source_data_collector.go
vra/data_source_region_enumeration.go
vra/resource_cloud_account_vmc.go
vra/resource_cloud_account_vsphere.go

For vRA 8.0, there is no data collector needed for vsphere and vmc resources. Hence, dcid is made optional.

Change data collector id to optional in support of vRA 8.0

---

vra/client.go
vra/client_test.go

Add the URL path into the transport to pass onto the API requests. Fixes #147.

Create transport with the requested URL path

---

.golangci.yml
vra/data_source_blueprint.go
vra/data_source_catalog_item.go
vra/data_source_cloud_account_gcp_test.go
vra/data_source_network_profile_test.go
vra/data_source_project.go
vra/data_source_project_test.go
vra/resource_blueprint.go
vra/resource_cloud_account_gcp_test.go
vra/resource_deployment.go
vra/resource_deployment_test.go
vra/resource_load_balancer_test.go
vra/resource_machine.go

This change enables golint within the golangci-lint suite of tests. For the most part it is renaming some variables with one additional "out-dent" of code around an "if with a return in it".

Fix golint issues and add to golangci-lint

---

vra/resource_project.go

Adding project resource field "shared_resources" which Specifies whether the resources in this projects are shared or not. If not set default will be used.
Signed-off-by: Vitalii Vinnichuk  <vinnichukvitaliy@gmail.com>

Adding project resource field "shared_resources"

---

vra/client.go
vra/data_source_deployment.go
vra/data_source_region_enumeration_vmc.go
vra/data_source_region_enumeration_vsphere.go
vra/resource_deployment.go

Region enumeration requests for vSphere and VMC sometime may take longer than
the default timeout of 30 seconds. Same is the case for deployment read
requests with expand resources, lastRequest, and Projects.
This commit increases the timeout for these requests from default 30 seconds
to 60 seconds.

Increase request timeouts for slow requests

---

scripts/release.sh

Add version information to plugin file so that terraform can display the
version when 'terraform -version' command is run.
Sample:
$ terraform -version
Terraform v0.12.21
+ provider.vra v0.1.8-6-g9b5854c
Fixes the issue #171.

Add version information to binary file

---

vra/resource_deployment.go

If inputs are changed in a deployment but the update action is not available
based on the current state of the deployment, the apply command fails immediately
without actually requesting for update action and getting failure from the service.

Fail early if deployment update is requested but not avaialble

---

examples/cloud_account_vsphere/README.md
examples/cloud_account_vsphere/main.tf
examples/cloud_account_vsphere/variables.tf
vra/data_source_cloud_account_nsxt.go
vra/data_source_cloud_account_nsxv.go
vra/data_source_cloud_account_vsphere.go
vra/resource_cloud_account_nsxt.go
vra/resource_cloud_account_nsxv.go
vra/resource_cloud_account_vsphere.go
vra/structure.go

Allow an existing NSX-T/V cloud account to be associated with a new vSphere
cloud account. Also update the state for vSphere and NSX-T/V cloud account
resources and data sources with associated cloud account ids if there are any.

Allow NSX-T/V accounts association with vSphere

---

examples/deployment/blueprint/main.tf
examples/deployment/catalog_item/main.tf
vra/data_source_deployment.go
vra/data_source_deployment_test.go
vra/deployment_request.go
vra/provider_test.go
vra/resource_deployment.go
vra/resource_project.go

For deployments failed mid-flight, state is not persisted correctly causing
the refresh to fail. This commit ensures that a deployment id is persisted
during create, so that even if the deployment fails or timesout, the
deployment resource is still created in the state and refresh works.
In case the provider times out before the deployment request completes i.e
successful or failed, refresh will pull the latest state of deployment.
For in-place updates of such deployment resources that timed out during
create should be untainted first.

Persist state for deployments that failed mid-flight

---

examples/project/README.md
examples/project/main.tf
examples/project/variables.tf
vra/data_source_project.go
vra/resource_project.go
vra/resource_project_test.go

vra_project resource now supports cpu, memory and storage limits on individual
zone assignments. Also vra_project data source now pulls the complete state
of the project into state file.

Fix 152 - Allow project creation with cpu, memory and storage limits

---

examples/project/main.tf
go.mod
go.sum
vra/resource_project.go

Update the SDK to latest version and allow the project not to
share resources provisioned thru this project.

Fix 187 - Allow project not to share resources

---

examples/content_source/README.md
examples/content_source/main.tf
examples/content_source/terraform.tfvars.sample
examples/content_source/variables.tf
examples/content_source/versions.tf
vra/content_source_repository_config.go
vra/provider.go
vra/provider_test.go
vra/resource_content_source.go
vra/resource_content_source_test.go

This PR adds support for a new resource ```vra_content_source``` leveraging the recent addition of the content api to vra-sdk-go. 
I've included an example, tests, and also a new struct ```ContentSourceRepositoryConfig``` in a standalone file to handle the content source repository config because it's required but not explicitly in the swagger model. 
This PR also includes a modified version of ```vra/data_source_region_enumeration.go``` as one of the side effects of the swagger hacks fix for region_enumeration in vra-sdk-go (https://github.com/vmware/vra-sdk-go/pull/12) resulted in a change in to the EnumerateVSphereRegions call from: 
```go
func (a *Client) EnumerateVSphereRegions(params *EnumerateVSphereRegionsParams) (*EnumerateVSphereRegionsOK, error) {
```
to: 
```go
func (a …
```

Added new resource content_source, also fix for region_enumeration

---

vra/client.go
vra/provider.go

Some installments of vRA have shorter access token expiry times and need
to control the reauthorization from a refresh token. Setting the provider
configuration reauthorize_timeout variable can control the duration used.
This variable takes a duration string such as "8h".

Add a reauthorize_timeout to the provider configuration

---

examples/catalog_item/README.md
examples/catalog_item/main.tf
examples/catalog_item/variables.tf
vra/data_source_blueprint_version.go
vra/data_source_blueprint_version_test.go
vra/data_source_catalog_source_blueprint.go
vra/data_source_catalog_source_blueprint_test.go
vra/data_source_catalog_source_entitlement.go
vra/data_source_catalog_source_entitlement_test.go
vra/provider.go
vra/resource_blueprint_test.go
vra/resource_blueprint_version.go
vra/resource_blueprint_version_test.go
vra/resource_catalog_source_blueprint.go
vra/resource_catalog_source_blueprint_test.go
vra/resource_catalog_source_entitlement.go
vra/resource_catalog_source_entitlement_test.go
vra/structure.go

This commit adds the resources and data sources needed in order to create
a blueprint version, release/unrelease it, create a new catalog source
for Cloud Assembly blueprint type, create a content entitlement (content
sharing) so that a blueprint created in Cloud Assembly is availble in
Service Broker Catalog.
Fixes #177.

Add functionality to publich a blueprint into Service Broker catalog

---

vra/resource_deployment.go
vra/resource_deployment_test.go

If a deployment is requested only with required inputs, upon successful
creation of deployment, the state file includes inputs not only that are
provided by the user in the config file, but also those with default
values in the blueprint/catalog item. Hence, when the plan/apply command
is run next time, the plan shows that the deployment state is changed and
it needs to update those deployment inputs that has default value with null.
This change introduces a new attribute 'inputs_including_defaults' with all
the inputs, i.e. both user provided and those with default values but not
provided by the user. The existing attribute 'inputs' includes only the
user provided inputs. These inputs provided by the user in the config file
are updated when deployment is updated in vRA directly and the …

Fix incorrect deployment update plans

---

examples/project/main.tf
vra/data_source_project.go
vra/resource_project.go

Add support of viewers, machine naming template and operation timeout properties
to Project resource and data source.
Fixes #211.

Add suppprt for viewers to Project resource and datasource

---

vra/deployment_request.go
vra/resource.go

Due to known limitations with TypeSet and recommendation described at
https://github.com/hashicorp/terraform/issues/25164#issuecomment-644356706,
the 'last_request' and 'resources' attributes in vra_deployment resource
are changed to TypeList so that they are updated correctly in the state
file at the time of running 'apply' command to update deployment resource,
which otherwise requires a 'refresh' command to update state file with the
correct state.

Fix deployment state persistence during apply commands

---

docs/get_token.sh

`return` can only be used in bash functions.

Exit if jq is not installed.

---

examples/cloud_account_nsxt/main.tf
examples/cloud_account_nsxt/terraform.tfvars.sample
examples/cloud_account_nsxt/variables.tf
examples/cloud_account_nsxv/main.tf
examples/cloud_account_nsxv/terraform.tfvars.sample
examples/cloud_account_nsxv/variables.tf
vra/resource_cloud_account_nsxt.go
vra/resource_cloud_account_nsxv.go

For creating a NSX-T/V cloud account, one doesn't need data collector
(dcId) with vRA 8.x. It is required only for vRA Cloud.
This commit makes the dcId as optional in schema for NSX-T/V cloud
account resources.

Make data collector id optional for NSX-T/V cloud accounts

---

vra/client.go
vra/data_source_deployment.go
vra/resource_deployment.go

With deployments apiVersion 2020-08-25, there are some changes that
are not backward compatible. To let the users continue to use the
provider with vRA 8.0, and 8.1, the deployments apiVersion is now
locked to 2019-01-15.

Lock deployments apiVersion to 2019-01-15

---

vra/resource_content_source.go

Addresses #250 Minor changes to vra_content_source to add support for bitbucket as a new repo source and ```TERRAFORM_CONFIGURATION``` as a new content type to go along with ABX_SCRIPTS,BLUEPRINT and IMAGE 
Signed-off-by: Carlos Tronco <cars@lostroncos.org>

updates for new content source options

---

go.mod
go.sum
vra/data_source_block_device.go
vra/data_source_storage_profile.go
vra/resource_block_device.go
vra/resource_storage_profile.go
vra/snapshots.go

Retrieve and include the snapshots information into the state file for 
block-device resource and data sources by setting `expand_snapshots`
to true in `vra_block_device` resource and data sources.

Include snapshots info for first class disk block-devices

---

examples/fabric_network_vsphere/README.md
examples/fabric_network_vsphere/main.tf
examples/fabric_network_vsphere/terraform.tfvars.sample
examples/fabric_network_vsphere/variables.tf
vra/provider.go
vra/resource_fabric_network.go
vra/resource_fabric_network_test.go

This PR addresses #224  by adding a new resource ```vra_fabric_network_vsphere```. Because this resource is one discovered by a vsphere cloud account it's behavior differs from other resources. Addition of this resource allows for management of more of the vRA configuration. 
* Create via ```apply``` will cause the provider to throw an error. 
* ```delete``` will simple remove the object from being managed and not affect the actual object in vRA
The process for using this is via
* ```import``` to get it into a managed state
* ```apply``` to apply settings from the config
Signed-off-by: Carlos Tronco <cars@lostroncos.org>

New import only resource vra_fabric_network_vsphere

---

examples/block-device/block-device-snapshot/README.md
examples/block-device/block-device-snapshot/main.tf
examples/block-device/block-device-snapshot/terraform.tfvars.sample
examples/block-device/block-device-snapshot/variables.tf
examples/block-device/block-device-snapshot/versions.tf
examples/block-device/main.tf
examples/block-device/versions.tf
go.mod
go.sum
vra/data_source_block_device_snapshots.go
vra/data_source_block_device_snapshots_test.go
vra/provider.go
vra/provider_test.go
vra/resource_block_device.go
vra/resource_block_device_snapshot.go
vra/resource_block_device_snapshot_test.go

Only vSphere first class disk is supported to create snapshots
Added unit tests for both resource and data source, also added examples
Update the block device snapshot is not supported

Add resource and data source for block_device_snapshot

---

examples/deployment/blueprint/main.tf
examples/deployment/catalog_item/main.tf
vra/deployment_request.go
vra/resource_deployment.go
vra/structure.go
vra/structure_test.go

This commit adds the support for  of array and object types in `vra_deployment` resource.
By default, all `TypeMap` properties in resource schema supports only primitive types and the values should be of type `string`  even when the `Elem` property is not specified. This is the same behavior even with terraform-plugin-sdk v2.
Hence, the inputs of 'array' and 'object' types from vRA cloud templates in `vra_deployment` resource should be provided in string format in Terraform configuration files.
Here's an example on how the inputs of different types can be specified in configuration file:
```
inputs = {
StringInput  = small
integerInput = 1
booleanInput = false
numberInput  = 10.0
arrayInput   = jsonencode([foo, bar, where, waldo])
objectInput  = jsonencode({ key1 : value1, key2 : [1, 2, …
```

Add support for deployment request inputs of array and object types

---

vra/provider.go
vra/resource_fabric_network_vsphere.go
vra/resource_fabric_network_vsphere_test.go
vra/resource_machine.go

Due to limitations to attach a first class vSphere disk to a machine during
provisioning as day-0 operation, the vra_machine resource create operation is
now changed to create the machine first without disks (even if given in the
configuration file) and then the disks are attached one by one as day-2 actions.
Also, the file name for vra_fabric_network_vsphere resource is modified to be
in consistent with other file names.

Allow vra_machine creation with first class vSphere disks

---

examples/cloud_account_nsxt/main.tf
vra/data_source_cloud_account_nsxt.go
vra/resource_cloud_account_nsxt.go

'vra_cloud_account_nsxt' resource and data sources are enhanced to show the mode of creation i.e. Manager vs. Policy.
By default, all new NSX-T cloud accounts are created in Policy mode in vRA 8.2 and vRA Cloud. If one want to create
NSX-T cloud account in legacy mode i.e. Manager mode, the property 'manager_mode' should be set to 'true'.
Fixes #257.

Enhance NSX-T cloud account to show the mode of creation

---

vra/resource_image_profile.go
vra/resource_zone.go
website/docs/r/vra_zone.html.markdown

With the latest SDK updates, an argument in a schema cannot have both Required and Default schema attributes.
This commit makes the 'placement_policy' in 'vra_zone' resource as optional as it has a default value.

Fix provider validation error in vra_zone resource

---

website/docs/d/vra_data_collector.html.markdown
website/docs/d/vra_region.html.markdown
website/docs/d/vra_region_enumeration.html.markdown
website/docs/d/vra_region_enumeration_aws.html.markdown
website/docs/d/vra_region_enumeration_azure.html.markdown
website/docs/d/vra_region_enumeration_gcp.html.markdown
website/docs/d/vra_region_enumeration_vmc.html.markdown
website/docs/d/vra_region_enumeration_vsphere.html.markdown

Add documentation for IaaS data sources:
data "vra_data_collector"
data "vra_region"
data "vra_region_enumeration"
data "vra_region_enumeration_aws"
data "vra_region_enumeration_azure"
data "vra_region_enumeration_gcp"
data "vra_region_enumeration_vmc"
data "vra_region_enumeration_vsphere"

Add documentation for data collector, region and region enumeration data sources

---

examples/cloud_account_vsphere/main.tf
examples/flavor_profile/main.tf
examples/flavor_profile/variables.tf
examples/flavor_profile/versions.tf
examples/network_profile/simple/versions.tf
examples/zone/versions.tf
vra/resource_cloud_account_vsphere.go
vra/resource_flavor_profile.go
vra/resource_network_profile.go
vra/resource_storage_profile.go
vra/resource_zone.go
website/docs/r/cloud_account_vsphere.html.markdown
website/docs/r/vra_flavor_profile.html.markdown
website/docs/r/vra_network_profile.html.markdown
website/docs/r/vra_zone.html.markdown

This commit fixes the missing fields while the resources are imported for
resources such as vra_cloud_account_vsphere, vra_zone, vra_flavor_profile,
vra_network_profile, and vra_storage_profile.

Fix misisng fields while importing resources

---

vra/data_source_project.go

The zone_assignments were not saved in state file when reading the project
as a data source. Fixed it by changing the type to type list from type set

[305] vra_project -> zone_assignments ignore multiple values

---

vra/data_source_zone.go
vra/resource_zone.go
website/docs/d/vra_zone.html.markdown
website/docs/r/vra_zone.html.markdown

In GET vra_zone, there is nor region_id. The region id is called
external region id in when a zone is read.
So, when creating a zone, a region id has to be provided. In the state file, the region id
is translated to external region id

[issue-323] Importing vRA Cloud Zone doesn't import region ID

---

.github/workflows/golangci-lint.yml
.github/workflows/release.yml
.golangci.yml
vra/data_source_deployment.go

* Upgrade `golangci-lint` to v1.41.1
* Remove deprecated `interfacer` linter
* Replace deprecated `golint` linter with `revive`
* Fix a linter issue

Update deprecated linters

---

vra/data_source_region.go

Fixed org_id and updated_at
Owner and created_at are missing from the API response. Opened a bug in vRA.
Once that is resolved, these two fields will be populated as well.

[Issue-347]Region data source returns null property values

---

examples/project/main.tf
vra/data_source_project.go
vra/resource_project.go
vra/user.go
website/docs/d/vra_project.html.markdown
website/docs/r/vra_project.html.markdown

Fix proposal is to deprecate the existing arguments for administrators, members, and viewers
and introduce new arguments to allow both email addresses and AD groups.

Allow AD groups as Project users

---

website/docs/r/cloud_account_vsphere.html.markdown

Field is defined as required in source code: https://github.com/vmware/terraform-provider-vra/blob/master/vra/resource_cloud_account_vsphere.go#L37
Signed-off-by:

Docs: Corrected field description to required

---

website/docs/index.html.markdown

Update the [provider's index page](https://registry.terraform.io/providers/vmware/vra/latest/docs) to reflect the correct product name, description, and links. It also removes the `Debugging options` section.
Fixes #350 

Update provider's index documentation

---

go.mod
go.sum
vra/data_source_deployment.go
vra/deployment_request.go
vra/resource.go
vra/resource_blueprint_test.go
vra/resource_deployment.go
vra/resource_deployment_test.go
vra/resource_project.go

Update the vra-sdk-go to [v0.2.21](https://github.com/vmware/vra-sdk-go/releases/tag/v0.2.21).

Update vRA SDKs to v0.2.21

---

vra/resource_deployment.go

* Fix delete deployment when there is an error (fixes #375)
* Show last request details when there is an error updating a deployment (fixes #372)

Fix delete and update deployment when there is an error

---

vra/data_source_region.go
website/docs/d/vra_region.html.markdown

Fix a bug introduced at #386.
Commit https://github.com/vmware/terraform-provider-vra/pull/386/commits/d1dba66f6a6f95526b4b64554e408755dc943909 introduced a regression when looking for the `region` parameter. Before the commit, `region` indicated the external region id. The change looked for the region name instead. This commit restores the previous way of looking for the `region` parameter.

Fix vra_region data source regression

---

.github/ISSUE_TEMPLATE/config.yml

Added GitHub Discussions to contact_links to encourage discussion and collaboration.
Signed-off-by: Ryan Johnson <johnsonryan@vmware.com>

Add GitHub Discussions to contact_links

---

examples/fabric_compute/README.md
examples/fabric_compute/main.tf
examples/fabric_compute/terraform.tfvars.sample
examples/fabric_compute/variables.tf
vra/data_source_fabric_compute.go
vra/data_source_fabric_compute_test.go
vra/provider.go
vra/provider_test.go
vra/resource_fabric_compute.go
vra/resource_fabric_compute_test.go
website/docs/d/fabric_compute.html.markdown
website/docs/r/fabric_compute.html.markdown

* Adds a new `fabric_compute` datasource, which can be used when assigning `compute resources` to a `zone` (see https://github.com/vmware/terraform-provider-vra/pull/391)
* Adds a new `fabric_compute` resource which can be imported and updated (Fixes https://github.com/vmware/terraform-provider-vra/issues/337)

Add `fabric_compute` datasource and resource

---

vra/data_source_fabric_datastore_vsphere.go

`fabric_datastore_vsphere` data source `id` attribute needs to be `computed` when lookup is performed by `filter`.
This was a regression introduced at https://github.com/vmware/terraform-provider-vra/pull/394/commits/9a40219e7933e0918c1f1251c5be10ee70d4344d.

Fix `fabric_datastore_vsphere` data source id attribute

---

vra/data_source_fabric_compute.go

`fabric_compute` data source `id` attribute needs to be `computed` when lookup is performed by `filter`

Fix `fabric_compute` data source id attribute

---

vra/data_source_deployment.go
vra/resource.go
vra/resource_deployment.go

Deployments API version '2020-08-25' only returns the summary of resources. In order to get all properties from resources, we have to make an explicit call. Fixes #427.

Fix retrieving deployment resources

---

docs/install_provider.md
website/docs/d/vra_image.html.markdown

- Updates the `d/vra_image` documentation with clearer content on required arguments and and (vSphere) example.
- Updates `tar xvf` to `unzip` for Linux in the **Installing the Provider** documentation I originally authored.
Resolves #441
Signed-off-by: Ryan Johnson <johnsonryan@vmware.com>

docs: update `d/vra_image` docs

---

vra/resource_deployment.go

When trying to re-deploy using blueprint_content it fails because blueprintID == "inline-blueprint"
Signed-off-by: Xiaolei Lin <linbcn10@gmail.com>

fix update deployment when using blueprint_content

---

vra/client.go
vra/data_source_deployment.go
vra/resource_deployment.go
vra/structure.go

The API to get the deployment resources returns a pageable response. By default, each page contains 20 resources.
Unfortunatelly, the client generated from the swagger specification does not allow to retrieve a specific page, so we can only retrieve the first page, leading to an incomplete list of resources when the deployment contains more than 20 resources.
As a workaround until the client supports proper pagination, we will increase the number of resources to be returned per page to 1000.

Return all deployment resources

---

examples/cloud_account_vsphere/main.tf
vra/resource_deployment.go

This was done because if a catalog item version is no longer available, the update function returns a 404 error. However, the blueprint version still exists and contains all the useful information we need to update a deployment.
We had an issue where an already deployment resource where no longer terraform compliant if a catalog item version was no longer available.
Also commented a line in the cloud_account_vsphere example.
Signed-off-by: an2ane <antoine.berlon@gmail.com>

Add blueprint schema fetch if catalog version not available during deployment update

---

CODE-OF-CONDUCT.md
CONTRIBUTING.md
README.md
RELEASE.md
docs/get_token.ps1
docs/get_token.sh
docs/getting_a_refresh_token.md
docs/install_provider.md
examples/block-device/README.md
website/docs/index.html.markdown

Updates use of "vRealize Automation" to "VMware Aria Automation" where applicable.

docs: brand updates

---

vra/provider.go
website/docs/index.html.markdown

- Updates `reauthorize_timeout` to accept `VRA_INSECURE`, and `VRA7_INSECURE`. Use of `VRA7_INSECURE` will trigger the depreciation notice.
- Updates `insecure` to accept `VRA_REAUTHORIZE_TIMEOUT`, and `VRA7_REAUTHORIZE_TIMEOUT`. Use of `VRA7_REAUTHORIZE_TIMEOUT` will trigger the depreciation notice.
- Updates documentation.
Closes #518

chore: deprecate `VRA7_` environmental variables

---

vra/resource_machine.go
website/docs/r/vra_machine.html.markdown

- Feature added based on request: https://github.com/vmware/terraform-provider-vra/issues/538 To be able to specify scsi controller and unit for block device attach
- Added support for attaching disks on build
Closes #538

feat: SCSI controller and unit number support, attach disks on build

---

vra/resource_zone.go
vra/resource_zone_test.go
website/docs/d/vra_zone.html.markdown
website/docs/r/vra_zone.html.markdown

- Adds `SPREAD_MEMORY` to `r/zone` `placement_policy`.
- Refactors to use constants for the placement policies and a var for the validation.
```shell
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccVRAZoneInvalidPlacementPolicy$ github.com/vmware/terraform-provider-vra/vra
=== RUN   TestAccVRAZoneInvalidPlacementPolicy
/Users/johnsonryan/Downloads/terraform-provider-vra/vra/resource_zone_test.go:168: Acceptance tests skipped unless env 'TF_ACC' set
--- SKIP: TestAccVRAZoneInvalidPlacementPolicy (0.00s)
PASS
ok      github.com/vmware/terraform-provider-vra/vra    0.946s
```
Closes #571

feat: add `SPREAD_MEMORY` to `r/zone` `placement_policy`

---

.github/workflows/stale.yml
.github/workflows/test.yml

Explicitly defines the permissions granted to the `GITHUB_TOKEN` used within the workflows.
By default, the `GITHUB_TOKEN` has broad write access. Limiting these permissions to only what the workflow actually needs.
https://github.com/vmware/terraform-provider-vra/security/code-scanning/2

chore(gh): update workflow permissions

---

docs/data-sources/vra_load_balancer.md
vra/data_source_load_balancer.go
vra/data_source_load_balancer_test.go
vra/provider.go
vra/resource_load_balancer_test.go

Adds support for `d/vra_load_balancer`.
Updates the test resource whitespace for allignment with `terraform fmt`.
```shell
=== RUN   TestAccVRALoadBalancerDataSource
data_source_load_balancer_test.go:22: Acceptance tests skipped unless env 'TF_ACC' set
--- SKIP: TestAccVRALoadBalancerDataSource (0.00s)
Test ignored.
PASS
Process finished with the exit code 0
```
Closes #529

feat: add `d/vra_load_balancer`
